### ISSUE TITLE
Enabling two factor 

### ISSUE THREAD

**Issue by Sinnbeck** [DarkGhostHunter/Laraguard#11]
In the part about enabling two factor, it is mentioned that it needs to be two way. Where do I send this in from?

```
$request->input('2fa_code')
```
Is there a route or a view I have missed?

**Comment by Sinnbeck** [comment]
Ok I get it now. I just create a view and pass the 2fa_code using an input/form.

**Comment by DarkGhostHunter** [comment]
I was gonna point just that.
