### ISSUE TITLE
Ajax support?

### ISSUE THREAD

**Issue by Sinnbeck** [DarkGhostHunter/Laraguard#12]
I assume this isn't going to happen considering how the package is built, using listeners. But are there any plans to make it possible to use with javascript/ajax? I am using inertia for a project where I would love to add two factor auth, but I need to have control over the response (`Inertia::render()`)

**Comment by DarkGhostHunter** [comment]
This package is not built around AJAX.

I'm not familiar with Inertia, but when you issue the login credentials through AJAX, [you will receive a 4XX code](https://github.com/DarkGhostHunter/Laraguard/blob/master/src/Listeners/EnforceTwoFactorAuth.php#L110). You can catch these codes, edit the view to make it AJAX-friendly and show it to the user when you receive it in your frontend.

It's not the best implementation but surely you can add a PR to add a AJAX-friendly form view.
