### ISSUE TITLE
MySQL 5.6 support

### ISSUE THREAD

**Issue by adamcmoore** [DarkGhostHunter/Laraguard#18]
The migration uses JSON field types which are not supported by MySQL 5.6.

Changing the fields to TEXT appears to work fine, but there is no way to publish the migration file to persist this change in our application.

**Comment by DarkGhostHunter** [comment]
I think this is resolved in #16 , but is pending merging.

**Comment by DarkGhostHunter** [comment]
Okay, here is the gist @adamcmoore : You can edit the migration file. So you can change the `json` field to `text`, and even the model you use for saving TOTP data.

Once merged, support for MySQL 5.6 should be fixed.

**Comment by adamcmoore** [comment]
Great, thanks for the quick reply. And thumbs up for the great package.

**Comment by DarkGhostHunter** [comment]
Should be fixed in v1.2.0
