### ISSUE TITLE
Question - TOTP verification on demand 

### ISSUE THREAD

**Issue by illambo** [DarkGhostHunter/Laraguard#20]
Hi, first of all thank you for the excellent work.
I was looking for a solution to verify an otp for certain operations (on demand), is it possible to trigger the otp verification flow manually or on custom events ?
Maybe like laravel middleware [_password.confirm_](https://laravel.com/docs/6.x/authentication#password-confirmation)
Thanks, regards

**Comment by DarkGhostHunter** [comment]
Nope, the package doesn't include that, but thanks for giving me the idea.

**Comment by 0x0range** [comment]
Are you looking to implement this feature? It would be really usefull if you edit some kind of secret stuff. For example if you want to edit a private key you need to enter the otp code.

**Comment by DarkGhostHunter** [comment]
Yes, but not now. I would preferably check a PR than add it myself.

It's not a walk in the park:

* If the user is not using 2FA, show generic view with activation.
* If the user has set the device as safe, don't confirm unless the middleware forces it.
* If the user is using safe devices, don't add this device unless the middleware forces it.

**Comment by DarkGhostHunter** [comment]
Plus: I will need some validation rules.

**Comment by DarkGhostHunter** [comment]
Available in 2.0, check it out.
