### ISSUE TITLE
Custom OTP name

### ISSUE THREAD

**Issue by danieljausovec** [DarkGhostHunter/Laraguard#21]
Hi.

Is it possible to set custom dynamic otp label name?

**Comment by DarkGhostHunter** [comment]
Nope. Could had a config for that, though.

**Comment by danieljausovec** [comment]
Yeah, that would be nice. Especially if someone want different names on environments.

**Comment by DarkGhostHunter** [comment]
I figured out initially that the labels should be the application name. It's non bc, so I'll as it later this weekend.

**Comment by DarkGhostHunter** [comment]
Figured out you can override the label yourself by just [changing the `getTwoFactorLabel()`](https://github.com/DarkGhostHunter/Laraguard/blob/65606312e68d556367580579608bca89a9e222e9/src/TwoFactorAuthentication.php#L95)

**Comment by danieljausovec** [comment]
I didn't mean label. I want to change issuer.

This is example what need to be changed.

Add config:
`'totp_issuer' => env('OTP_TOTP_ISSUER', '')`

Change `toUri` function in `SerializesSharedSecret` trait like this:
```
$query = http_build_query([
    'issuer'    => $issuer = config('laraguard.totp_issuer'),
    'label'     => $this->attributes['label'],
    'secret'    => $this->shared_secret,
    'algorithm' => strtoupper($this->attributes['algorithm']),
    'digits'     => $this->attributes['digits'],
], null, '&', PHP_QUERY_RFC3986);

return "otpauth://totp/".rawurlencode($issuer)."%3A{$this->attributes['label']}?$query";
```

Can you please implement this? Thanks.

**Comment by DarkGhostHunter** [comment]
No prob, I'll add it.

**Comment by DarkGhostHunter** [comment]
[Added in v1.13.0](https://github.com/DarkGhostHunter/Laraguard/releases/tag/v1.3.0)
