### ISSUE TITLE
notice not working well

### ISSUE THREAD

**Issue by FleiTec** [DarkGhostHunter/Laraguard#22]
Hi.
When i do all like installation guide in readme. I got an error:

`
Facade\Ignition\Exceptions\ViewException
Undefined variable: url (View: /var/www/html/beta9/resources/views/vendor/laraguard/notice.blade.php)
http://domain.com/2fa-required
Hide solutions
$url is undefined
Make the variable optional in the blade template. Replace {{ $url }} with {{ $url ?? '' }}
`

Any ideas?

Thanks

**Comment by DarkGhostHunter** [comment]
Ah, the Middleware redirects to the view, but the view doesn't gets the `$url`. I'll fix it by making it optional, since the idea is to have a controller behind to handle the view and include the URL variable to where the user can enable 2FA.
