### ISSUE TITLE
Serialization of 'Closure' is not allowed 

### ISSUE THREAD

**Issue by MazettePatacaisse** [DarkGhostHunter/Laraguard#27]
Laravel 7.12

Exception
Serialization of 'Closure' is not allowed 

error appear when Laraguard package is  installed. It appears on successfull request login and only on no 2fa user accounts

**Comment by DarkGhostHunter** [comment]
Show the full stack trace.

**Comment by MazettePatacaisse** [comment]
this is the stacktrace

https://flareapp.io/share/w5BRpd58

**Comment by MazettePatacaisse** [comment]
Solution here. It was another package

https://stackoverflow.com/questions/55318809/laravel-serialization-of-closure-is-not-allowed
