### ISSUE TITLE
Can't run migration: index name too long

### ISSUE THREAD

**Issue by NEGits** [DarkGhostHunter/Laraguard#4]
- Laravel Version: 6.14.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7.27

When running included migration I get the following error:

```
SQLSTATE[42000]: Syntax error or access violation: 
1059 Identifier name 'two_factor_authentications_authenticatable_type_authenticatable_id_index' is too long 
(SQL: alter table `two_factor_authentications` add index `two_factor_authentications_authenticatable_type_authenticatable_id_index`(`authenticatable_type`, `authenticatable_id`))
```

A shorter index name [here](https://github.com/DarkGhostHunter/Laraguard/blob/b01c3881d41ee59cb79a382eeec5385f072bc90f/database/migrations/2020_01_01_000000_create_two_factor_authentications_table.php#L18) should fix this I guess?

**Comment by DarkGhostHunter** [comment]
MySQL has a limit of 64, MariaDB of 80, PostgreSQL has 63 and truncates, and SQL Server has 128. SQLite doesn't care as long you don't go overboard the query characters limit.

Yeah, that seems like a long index. I will use this once I out my hands on the computer. The morphs method creates an index automatically, but AFAIK you can just go manual and do it yourself.

**Comment by DarkGhostHunter** [comment]
Lol, you can add the index name to the `morph()` method. It should be fixed on the next release.

**Comment by DarkGhostHunter** [comment]
Good news: is fixed.

Bad news: Laravel 6.15 includes the Validated event, which makes the whole thing error. Unless I refactor the package to handle both events (Attempting and Validated), this gonna take a while.

**Comment by DarkGhostHunter** [comment]
Damn. I'll have to (again) take down the package for a simple reason: I can't test if a class doesn't exists. Major rework is needed.

**I deeply sorry for all headaches caused**, but for sanity purposes I will make the rewrite easier and only compatible with Laravel 6.15+.
