### ISSUE TITLE
Not prompted for 2FA on login

### ISSUE THREAD

**Issue by maciekish** [DarkGhostHunter/Laraguard#40]
Hi, i just added your package to my Laravel 7 installation on PHP 7.4. I added the Contract and Trait to my User model, ran the migration and published the config without any changes. 

I was able to sucessfully generate and confirm my 2FA code and $user->hasTwoFactorEnabled() returns true. 

But when i log out and try logging back in again, i'm logged in without any request for a 2fa code! I can log in using the password only.

What have i missed?

**Comment by maciekish** [comment]
I finally figured out that i had to add `DarkGhostHunter\Laraguard\LaraguardServiceProvider::class` to my providers in app.php. I believe Laravel is supposed to auto-load these, no?

**Comment by DarkGhostHunter** [comment]
No problems on my end. You may have package discord disabled in your composer file.
