### ISSUE TITLE
Brute force Confirm code

### ISSUE THREAD

**Issue by dragonfly4** [DarkGhostHunter/Laraguard#42]
Hello,

Are you planning to extend the totp_code rule [ [TotpCodeRule](https://github.com/DarkGhostHunter/Laraguard/blob/master/src/Rules/TotpCodeRule.php) ] with an anti brute-force check please?

The Confirm controller has no checks. This could be a potential security risk.

**Comment by DarkGhostHunter** [comment]
Good idea.

**Comment by DarkGhostHunter** [comment]
As the package is developed, brute-force attacks must be protected by the developer itself, at per-route level. Nothing I can do.
