### ISSUE TITLE
Safe devices - let user decide

### ISSUE THREAD

**Issue by mtveerman** [DarkGhostHunter/Laraguard#47]
Currently, the `safe devices` option is activated in the config. So it is activated globally. 

Let's assume I am on a public computer. When I login successfully, the device is marked as `safe device`, while it is not.

Currently there is no option for a user loging in to manually mark a computer as safe:
https://github.com/DarkGhostHunter/Laraguard/blob/master/src/Listeners/EnforceTwoFactorAuth.php#L87

What if we add something like:
```php
if (request()->input('is_safe', false)) {
   // Safe device
}
```
(Maybe there is a way to code it without being a breaking change)

**Comment by DarkGhostHunter** [comment]
Good idea. On the view I can add a checkbox that says "Don't ask for codes on this device". Once, it gets tot he app, we will check if the checkbox is filled, and add it as a safe device.

By the way, I'm trying to take out the credentials from the view for added security, as discussed in #46.

**Comment by DarkGhostHunter** [comment]
https://github.com/DarkGhostHunter/Laraguard/releases/tag/v3.0.0
