### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by TKlie** [DarkGhostHunter/Laraguard#50]
Hey,

First off: thanks for this great package.
Secondly: Do you plan on releasing a Laravel 8 compatible version any time soon?

Regards

**Comment by DarkGhostHunter** [comment]
As soon I'm free. Currently in another project.

**Comment by RicLeP** [comment]
It will install with composer require darkghosthunter/laraguard:dev-master - I’ve not test if it functions though.

**Comment by DarkGhostHunter** [comment]
PHP 8.0 comes with Laravel 8.0 compatibility.

**Comment by DarkGhostHunter** [comment]
https://github.com/DarkGhostHunter/Laraguard/releases/tag/v3.0.0
