### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by oriceon** [DarkGhostHunter/Laraguard#51]

**Comment by caophong** [comment]
Do you have a roadmap for php8?

**Comment by denydias** [comment]
php8 is becoming increasingly common among Linux distributions. It would be great to have a word on if/when php8 support will be added to Laraguard so developers counting on this great package could plan themselves for this important php milestone.

**Comment by DarkGhostHunter** [comment]
It will be added this week. Will come with a change to handle binary (will use BASE64 instead, will bring more compatibility on databases but more memory consumption, sorry).

So, yes, incoming.

**Comment by denydias** [comment]
It's great to hear from you again, @DarkGhostHunter!

I'm glad to know that php8 support is coming, despite the increased memory usage.

**Comment by DarkGhostHunter** [comment]
> It's great to hear from you again, @DarkGhostHunter!
> 
> I'm glad to know that php8 support is coming, despite the increased memory usage.

I think it would have less memory consumption, but anyway, here is:

https://github.com/DarkGhostHunter/Laraguard/releases/tag/v3.0.0
