### ISSUE TITLE
Use with Uuid

### ISSUE THREAD

**Issue by MrMooky** [DarkGhostHunter/Laraguard#54]
Is this package compatible with the user model id being a uuid? I'm not sure if I can just change the migration without breaking anything inside the package.

My idea was to change / replace the line

```
$table->morphs('authenticatable', '2fa_auth_type_auth_id_index');
```

with this:

```
$table->string('authenticatable_type');
$table->uuid('authenticatable_id');
```

Would that work, of break any logic inside the package itself?

**Comment by MrMooky** [comment]
It seems to work. Would still like to know if this could have any implications somewhere.

**Comment by DarkGhostHunter** [comment]
Use [`uuidMorphs()`](https://laravel.com/docs/8.x/migrations#column-method-uuidMorphs). You shouldn't have problems as the morphs `id` only changes the type.
