### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by MrMooky** [DarkGhostHunter/Laraguard#55]
Is there any way to supply an application logo when using the QR code? For some strange reason it says "SIPPEL" for my app and I don't even know what that is. o_O

This is with Authy after I scan the QR code:

![IMG_0242](https://user-images.githubusercontent.com/3603346/115029288-20723180-9ec6-11eb-89f1-6f2e33b9c290.jpeg)

**Comment by DarkGhostHunter** [comment]
> Is there any way to supply an application logo when using the QR code? 

No, the QR only contains the URL to [create the TOTP](https://github.com/DarkGhostHunter/Laraguard/blob/v3.0.0/src/Eloquent/SerializesSharedSecret.php#L27).

> For some strange reason it says "SIPPEL" for my app and I don't even know what that is. o_O
>
> This is with Authy after I scan the QR code:
> 
> ![IMG_0242](https://user-images.githubusercontent.com/3603346/115029288-20723180-9ec6-11eb-89f1-6f2e33b9c290.jpeg)

It's on Authy end IMO, dunno "where" it takes that SIPPEL thing. Maybe it's part of you server. Try with another authenticator.

**Comment by MrMooky** [comment]
Mh, that was not the answer I was hoping for. Have to try another package then.
