### ISSUE TITLE
Attempt in Livewire component

### ISSUE THREAD

**Issue by abdosaeedelhassan** [DarkGhostHunter/Laraguard#57]
i have login page in livewire component when attempt username and password, it shown like follow
https://www.loom.com/share/2c6bf95d7b1f4934823e7f6649520e55
my question how i can redirect to auth view manually or fired event to call check auth code view

**Comment by abdosaeedelhassan** [comment]
I solved my problem using 2fa.confirm middleware, thank you

**Comment by aeq-dev** [comment]
Hello @abdosaeedelhassan 
Could you please tell me how did you setup you login form and routes ? 
I want to ask user for the 2fa_code just after he successfully login same as you did in demo.
Thanks

**Comment by DarkGhostHunter** [comment]
Use `attemptWhen()` on your `Auth` facade.
