### ISSUE TITLE
Control by Admin user

### ISSUE THREAD

**Issue by abdosaeedelhassan** [DarkGhostHunter/Laraguard#58]
firstly thank you for **Laraguard** it is a great work.
sometimes need admin users control other users guard like update recovery codes or disable tow factor recovery from specific user, is there any plan to do something like this?, i can help in this upgrade work, thank you

**Comment by DarkGhostHunter** [comment]
It's outside the scope of the package, but you can always create your own admin panel for that with a few controllers:

```php
public controller reset(User $user)
{
    $user->generateRecoveryCodes();

    $user->notify(new GeneratedRecoveryCodes());

    return back();
}
```

**Comment by abdosaeedelhassan** [comment]
Thank you
