### ISSUE TITLE
[Question] Laravel Passport Integration

### ISSUE THREAD

**Issue by lucianobosco** [DarkGhostHunter/Laraguard#60]
Hi! This looks like such a nice library. 
I'm wondering if can be integrated with Laravel Passport or any OAuth2 server implementation.
I'm working with Vue Js as a front-end and Laravel as a Rest API service. It would be great to have this working on my projects.

Thanks!

**Comment by DarkGhostHunter** [comment]
Not out of the box, as it uses a custom driver. You could extend Passport driver for a check on WebAuthn Credentials.
