### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by padre** [DarkGhostHunter/Laraguard#7]
When I run:

`php artisan vendor:publish --provider=DarkGhostHunter\Laraguard\LaraguardServiceProvider`

I had to add double quotes:

`php artisan vendor:publish --provider="DarkGhostHunter\Laraguard\LaraguardServiceProvider"`

Thanks!

**Comment by DarkGhostHunter** [comment]
I always forget the double quotes. I'll fix it in the readme.

**Comment by DarkGhostHunter** [comment]
[Done!](https://github.com/DarkGhostHunter/Laraguard/commit/b78b2ae3786f9e0188985fdbe3fb657916272b7f)
