### ISSUE TITLE
Bug on Recovery Code in Login

### ISSUE THREAD

**Issue by aeq-dev** [DarkGhostHunter/Laraguard#72]
Hello,
I've just detected a bug when we use recovery code in login instead of TOTP, the reason is the rule validation here :
```
 protected function requestHasCode(): bool
    {
        return !validator($this->request->only($this->input), [
            $this->input => 'required|numeric',
        ])->fails();
    }

```
You need to remove 'numeric' to get true for recovery code.
Regards

**Comment by DarkGhostHunter** [comment]
Could you send a PR? Kinda busy.

**Comment by DarkGhostHunter** [comment]
This fix was simple: I changed `numeric` for `alpha_num`.

TOTP Codes are entirely numeric. Recovery Codes are alphanumeric.
