### ISSUE TITLE
Suggestion: getAvailableCodes

### ISSUE THREAD

**Issue by aeq-dev** [DarkGhostHunter/Laraguard#73]
Hi,
You may add this scope to get only available codes, something like this :

```
 public function getAvailableCodes(): Collection
    {
        return $this->twoFactorAuth->recovery_codes->whereNull('used_at') ?? collect();
    }
```

Thanks

**Comment by DarkGhostHunter** [comment]
Sorry but I don't see a compelling reason to add a getter since you can add it to your model instead.
